### ISSUE TITLE
LightHouse 접근성 지표 개선

### ISSUE THREAD

**Issue by inkyu0103** [inkyu0103/badminton-app#114]
# 설명

사용자에게 더 나은 경험을 제공하기 위해 LightHouse 성능 지표중 접근성 지표를 개선합니다.

다음은 local 환경에서의 LightHouse 지표입니다.

![image](https://github.com/inkyu0103/badminton-app/assets/48270642/ff955fd4-48dd-4fef-9041-c0ff1acc84c1)

**TODO**
- [x] `<title>` 요소 추가
- [x] 링크에 인식 가능한 이름 포함
- [x] 다국어화 및 현지화 설정
