### ISSUE TITLE
유저 이메일 인증 플로우를 생성합니다.

### ISSUE THREAD

**Issue by inkyu0103** [inkyu0103/badminton-app#36]
# 설명
회원가입 방식 중, 기본적으로 이메일 인증 플로우를 사용합니다.
FE / BE 이슈를 이 Epic 이슈에서 관리합니다.

# TODO
- [x] 이메일 인증 플로우 도식화
**FE**
- [x] 사용될 이메일 템플릿 퍼블리싱
**BE**
- [x] 백엔드 API 생성
  - [x] 이메일 전송 API
  - [x] 회원가입 API
