### ISSUE TITLE
이메일 토큰 유효성 검증 API 개발

### ISSUE THREAD

**Issue by inkyu0103** [inkyu0103/badminton-app#42]
# 설명

회원가입을 위해 전달한 이메일에는, 회원가입을 요청한 이메일이 url이 포함되어 전달됩니다.
해당 이메일의 유효성을 검증하기 위한 API를 개발합니다.

또한, 회원 가입 인증 메일 전송 후 1시간이 지나면, Verification 테이블에서 자동으로 삭제할 수 있도록, 스케줄링 옵션을 사용합니다.

**Comment by inkyu0103** [comment]
### TODO
- [x] createdAt과 JWT Expire값을 둘 다 사용하는 이유 
  - createdAt는 db cron job을 실행할 때 delete 대상인지 판별하기 위해 사용됩니다.
  - JWT Expire은 유효성 검증을 위해 사용합니다.
- [x] 스케줄링 방법 조사 -> Raw query or pg_cron
- [x] 로직 도식화 하기 
- [x] nestjs Guard 개념 적용 가능한지 확인
    - guard는 특정 request 또는 모든 request에 대해서 이 요청이 유효한 사용자로부터 온 것인지 확인하는데 사용됩니다. (커스텀 하기 나름) 이메일 토큰이 유효한지 요청하는 route에 local guard를 사용하는 것은 가능해 보입니다.
